// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// Root layout with Tailwind CSS
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Next.js Cron Job App</title>
        <meta name="description" content="Cron job implementation with Next.js and Tailwind CSS" />
      </head>
      <body>{children}</body>
    </html>
  );
}